In [1]:
import os
import pickle
import numpy as np
import tensorflow as tf
import tensorflow.keras.backend as K
from tensorflow.keras.models import Model, clone_model, model_from_json
from tensorflow.keras.layers import Dense, Input, Average, Lambda, Flatten, Reshape, BatchNormalization, Layer, Masking, LSTM
from tensorflow.keras.losses import binary_crossentropy
from tensorflow.keras.callbacks import ReduceLROnPlateau, ModelCheckpoint, EarlyStopping
from sklearn.model_selection import KFold

In [2]:
kf = KFold(n_splits=5, shuffle=True, random_state=0)

In [13]:
X_trainval = np.arange(100)

In [40]:
for fold, (train_indices, val_indices) in enumerate(kf.split(X_trainval)):
    print(fold)
    print(len(train_indices))
    print(len(val_indices))

0
80
20
1
80
20
2
80
20
3
80
20
4
80
20


In [15]:
class Singer(object):
    def __init__(self, lylics):
        self.lylics = lylics
    def sing(self):
        print(self.lylics)

In [16]:
import pickle

singer = Singer('Shanranran')

with open('singer.pickle', 'wb') as f:
    pickle.dump(singer, f)

In [17]:
# "インスタンス化したあと"の状態を保持してくれる
with open('singer.pickle', 'rb') as f:
    singer = pickle.load(f)

singer.sing()

Shanranran


In [18]:
kernel_initializer_dict = {"relu": "he_normal"}

In [31]:
hidden_layers_list[0]

In [25]:
hidden_layers_list = [Dense(20, activation="relu", kernel_initializer=kernel_initializer_dict.get("relu"), name=f"hidden_{i + 1}") for i in range(4)]

In [38]:
lr_dict = {"adam":0.2,"sgd":9}

In [39]:
lr_dict.get("adam")

0.2

In [41]:
test_data = np.arange(300)
index_1 = np.arange(3)
print(index_1)
index_2 = np.arange(30)
print(index_2)
index_3 = np.arange(300)

[0 1 2]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [124]:
index_1 = np.repeat(index_1.copy(),100)
index_2 = np.repeat(index_2.copy(),10)

In [51]:
data_tot = np.array([index_1,index_2,index_3,test_data]).T

In [52]:
import pandas as pd
data_tot = pd.DataFrame(data_tot)

In [60]:
data_tot.columns = ["100","10","1","data"]

In [61]:
data_tot.head()

100  10  1  data
0    0   0  0     0
1    0   0  1     1
2    0   0  2     2
3    0   0  3     3
4    0   0  4     4

In [63]:
data_tot.set_index(["100","10","1",], inplace = True)

In [81]:
data_tot.index.get_level_values("10").unique()

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
           dtype='int64', name='10')

In [103]:
data_grouped = data_tot_2.groupby(by=['100', '10'])

In [171]:
name_list = np.array(list(data_grouped.indices.keys()))

In [161]:
kf = KFold(n_splits=5, shuffle=True, random_state=0)


In [174]:
# prepare datasets of dataframe for training and validation from dataframe
# data_totの部分にdf_gbを入れて交差検証用のデータを粒界の種類ごとに抽出する
data_grouped = data_tot_2.groupby(by=['100', '10']) # by [element, axis, gbindex]
name_list = np.array(list(data_grouped.indices.keys()))
for fold, (train_indices, val_indices) in enumerate(kf.split(name_list)):
    # Prepare dataset
    print(f"fold_number = {fold}")
    X_train_indices, X_val_indices = name_list[train_indices], name_list[val_indices]
    X_train_indices = list([tuple(e) for e in X_train_indices])
    X_val_indices = list([tuple(e) for e in X_val_indices])
    print(X_val_indices)
    group_1 = pd.concat([data_grouped.get_group(group_name) for group_name in X_val_indices])
    print(group_1)
    # returnされるのは訓練用データが入ったデータフレームと検証用データが入ったデータフレーム

fold_number = 0
[(0, 2), (1, 10), (1, 13), (2, 24), (2, 26), (2, 28)]
            data
100 10 1        
0   2  20     20
       21     21
       22     22
       23     23
       24     24
...          ...
2   28 285   285
       286   286
       287   287
       288   288
       289   289

[120 rows x 1 columns]
fold_number = 1
[(0, 5), (1, 11), (1, 16), (1, 17), (2, 22), (2, 27)]
            data
100 10 1        
0   5  50     50
       51     51
       52     52
       53     53
       54     54
...          ...
2   27 275   275
       276   276
       277   277
       278   278
       279   279

[120 rows x 1 columns]
fold_number = 2
[(0, 1), (0, 8), (1, 14), (2, 20), (2, 23), (2, 29)]
            data
100 10 1        
0   1  10     10
       11     11
       12     12
       13     13
       14     14
...          ...
2   29 295   295
       296   296
       297   297
       298   298
       299   299

[120 rows x 1 columns]
fold_number = 3
[(0, 4), (0, 6), (0, 7), (0, 9), (1, 18)

In [122]:
group_1 = pd.concat([data_grouped.get_group(group_name) for X in gname_list])

In [175]:
vector = np.arange(10)
print(vector)
vector = vector.reshape(vector.shape[0], -1)
print(vector)

[0 1 2 3 4 5 6 7 8 9]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
